"""comments to posts

Revision ID: 290663e4cab6
Revises: 34afd4a5414f
Create Date: 2015-02-08 12:09:25.263187

"""

# revision identifiers, used by Alembic.
revision = '290663e4cab6'
down_revision = '34afd4a5414f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'post_id')
    ### end Alembic commands ###
