"""Settings table

Revision ID: 4a089a2f3f63
Revises: 333c486a613f
Create Date: 2015-07-10 00:57:23.571702

"""

# revision identifiers, used by Alembic.
revision = '4a089a2f3f63'
down_revision = '333c486a613f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    ### end Alembic commands ###
