"""Deleted flag for user

Revision ID: 5661c7799699
Revises: 33312d294707
Create Date: 2015-03-05 01:49:59.910577

"""

# revision identifiers, used by Alembic.
revision = '5661c7799699'
down_revision = '33312d294707'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    ### end Alembic commands ###
