"""User Oauth

Revision ID: 599e7a495734
Revises: 177929347b0
Create Date: 2015-02-20 03:14:33.559868

"""

# revision identifiers, used by Alembic.
revision = '599e7a495734'
down_revision = '177929347b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('service_user_id', sa.String(length=80), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_oauth')
    ### end Alembic commands ###
