"""signup date

Revision ID: b72cb32a371
Revises: 4aac077d09ca
Create Date: 2015-02-25 23:28:04.981867

"""

# revision identifiers, used by Alembic.
revision = 'b72cb32a371'
down_revision = '4aac077d09ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signup_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signup_date')
    ### end Alembic commands ###
