"""post types

Revision ID: 121cc3fd9dec
Revises: 3ad7c115bbca
Create Date: 2015-02-08 18:23:51.306917

"""

# revision identifiers, used by Alembic.
revision = '121cc3fd9dec'
down_revision = '3ad7c115bbca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'post', sa.Column('post_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'post_type', ['post_type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column(u'post', 'post_type_id')
    op.drop_table('post_type')
    ### end Alembic commands ###
