"""imgur deletehash

Revision ID: 177929347b0
Revises: 121cc3fd9dec
Create Date: 2015-02-08 22:08:21.733632

"""

# revision identifiers, used by Alembic.
revision = '177929347b0'
down_revision = '121cc3fd9dec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('picture_deletehash', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'picture_deletehash')
    ### end Alembic commands ###
