"""post tweaks

Revision ID: 2fac31c2a955
Revises: 528338eceb85
Create Date: 2015-02-07 22:56:54.867853

"""

# revision identifiers, used by Alembic.
revision = '2fac31c2a955'
down_revision = '528338eceb85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'uuid',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    op.create_unique_constraint(None, 'post', ['uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.alter_column('post', 'uuid',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    ### end Alembic commands ###
