"""Unique username

Revision ID: 33312d294707
Revises: 43bf2e6167e0
Create Date: 2015-03-03 22:42:10.666988

"""

# revision identifiers, used by Alembic.
revision = '33312d294707'
down_revision = '43bf2e6167e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
