"""Contexts for notification subscriptions

Revision ID: 333c486a613f
Revises: 5747fc882218
Create Date: 2015-07-08 23:38:46.958918

"""

# revision identifiers, used by Alembic.
revision = '333c486a613f'
down_revision = '5747fc882218'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_subscriptions', sa.Column('context_object_id', sa.Integer(), nullable=False))
    op.add_column('notification_subscriptions', sa.Column('context_object_type_id', sa.Integer(), nullable=False))
    op.drop_column('notification_subscriptions', 'object_id')
    op.drop_column('notification_subscriptions', 'object_type_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_subscriptions', sa.Column('object_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('notification_subscriptions', sa.Column('object_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('notification_subscriptions', 'context_object_type_id')
    op.drop_column('notification_subscriptions', 'context_object_id')
    ### end Alembic commands ###
