"""dropping unique keys

Revision ID: 43bf2e6167e0
Revises: b72cb32a371
Create Date: 2015-02-26 01:24:29.878327

"""

# revision identifiers, used by Alembic.
revision = '43bf2e6167e0'
down_revision = 'b72cb32a371'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'uuid', 'comment', type_='unique')
    op.drop_constraint(u'uuid', 'post', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uuid', 'post', ['uuid'], unique=True)
    op.create_index('uuid', 'comment', ['uuid'], unique=True)
    ### end Alembic commands ###
