"""Post and comment status and flagging

Revision ID: 4aac077d09ca
Revises: 550466333278
Create Date: 2015-02-25 01:04:11.945746

"""

# revision identifiers, used by Alembic.
revision = '4aac077d09ca'
down_revision = '550466333278'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('status', sa.String(length=12), nullable=True))
    op.add_column('post', sa.Column('status', sa.String(length=12), nullable=True))
    op.add_column('user_comment_rating', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    op.add_column('user_post_rating', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_post_rating', 'is_flagged')
    op.drop_column('user_comment_rating', 'is_flagged')
    op.drop_column('post', 'status')
    op.drop_column('comment', 'status')
    ### end Alembic commands ###
