"""hot value in database

Revision ID: 544ae4180eb
Revises: 599e7a495734
Create Date: 2015-02-22 21:49:31.247927

"""

# revision identifiers, used by Alembic.
revision = '544ae4180eb'
down_revision = '599e7a495734'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_rating', sa.Column('hot', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_rating', 'hot')
    ### end Alembic commands ###
