# Generated by Django 2.2.2 on 2020-01-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0002_add_profile_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmediavideo',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
