# Generated by Django 2.2.2 on 2020-01-31 00:10

import dillo.models
from django.conf import settings
from django.db import migrations, models

import dillo.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dillo', '0003_add_video_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(max_length=120)),
                (
                    'visibility',
                    models.CharField(
                        choices=[
                            ('public', 'Public'),
                            ('unlisted', 'Unlisted'),
                            ('private', 'Private'),
                        ],
                        default='private',
                        max_length=20,
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        height_field='avatar_height',
                        upload_to=dillo.models.mixins.get_upload_to_hashed_path,
                        width_field='avatar_width',
                    ),
                ),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
