# Generated by Django 2.2.2 on 2020-02-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0005_event_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarks', to='dillo.Post'),
        ),
    ]
