# Generated by Django 2.2.2 on 2020-02-26 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0006_add_profile_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='setup_stage',
            field=models.CharField(
                choices=[
                    ('picture', 'Picture'),
                    ('bio', 'Bio'),
                    ('links', 'links'),
                    ('tags', 'Tags'),
                ],
                default='picture',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(
                choices=[('public', 'Public'), ('unlisted', 'Unlisted')],
                default='public',
                max_length=20,
            ),
        ),
    ]
