# Generated by Django 2.2.2 on 2020-03-01 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dillo', '0008_picture_to_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='setup_stage',
            field=models.CharField(
                blank=True,
                choices=[
                    ('avatar', 'Avatar'),
                    ('bio', 'Bio'),
                    ('links', 'links'),
                    ('tags', 'Tags'),
                ],
                default='avatar',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='date created'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('message', models.TextField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
    ]
