# Generated by Django 2.2.2 on 2020-03-04 20:01

import dillo.models.mixins
import dillo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0012_likes_for_shorts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile', old_name='header_height', new_name='reel_thumbnail_16_9_height',
        ),
        migrations.RenameField(
            model_name='profile', old_name='header_width', new_name='reel_thumbnail_16_9_width',
        ),
        migrations.RemoveField(model_name='profile', name='header',),
        migrations.AddField(
            model_name='profile',
            name='reel_thumbnail_16_9',
            field=models.ImageField(
                blank=True,
                height_field='reel_thumbnail_16_9_height',
                upload_to=dillo.models.mixins.get_upload_to_hashed_path,
                width_field='reel_thumbnail_16_9_width',
            ),
        ),
        migrations.AlterField(
            model_name='short',
            name='url',
            field=models.URLField(
                help_text='A YouTube or Vimeo link',
                max_length=120,
                validators=[dillo.validators.validate_reel_url],
            ),
        ),
    ]
