# Generated by Django 2.2.2 on 2020-03-04 22:56

import dillo.models.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dillo', '0013_header_to_reel_thumbnail_16_9'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='date created'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('title', models.CharField(help_text='E.g. Animation Director', max_length=255)),
                (
                    'contract_type',
                    models.CharField(
                        choices=[
                            ('permanent', 'Permanent'),
                            ('freelance', 'Freelance'),
                            ('internship', 'Internship'),
                        ],
                        default='permanent',
                        max_length=255,
                    ),
                ),
                ('is_remote_friendly', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('studio_website', models.URLField(blank=True, max_length=120)),
                ('url_apply', models.URLField(max_length=550)),
                (
                    'visibility',
                    models.CharField(
                        choices=[('public', 'Public'), ('unlisted', 'Unlisted')],
                        default='public',
                        max_length=20,
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        height_field='image_height',
                        upload_to=dillo.models.mixins.get_upload_to_hashed_path,
                        width_field='image_width',
                    ),
                ),
                ('image_height', models.PositiveIntegerField(null=True)),
                ('image_width', models.PositiveIntegerField(null=True)),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        help_text='A comma-separated list of tags.',
                        through='taggit.TaggedItem',
                        to='taggit.Tag',
                        verbose_name='Tags',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
    ]
