# Generated by Django 2.2.2 on 2020-03-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0014_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='starts at'),
        ),
    ]
