# Generated by Django 2.2.2 on 2020-03-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0015_jobs_add_starts_at'),
    ]

    operations = [
        migrations.RenameField(model_name='job', old_name='state', new_name='country',),
        migrations.RenameField(model_name='job', old_name='province', new_name='province_state',),
    ]
