# Generated by Django 2.2.11 on 2020-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0016_jobs_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='starts_at',
            field=models.DateField(blank=True, null=True, verbose_name='starts at'),
        ),
    ]
