# Generated by Django 2.2.11 on 2020-03-12 23:55

import dillo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0017_jobs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmediavideo',
            name='encoding_job_progress',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(
                blank=True,
                help_text='Your place in the world. Usually "City, Country"',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reel',
            field=models.URLField(
                blank=True,
                help_text='A YouTube or Vimeo link to your demo reel.',
                validators=[dillo.validators.validate_reel_url],
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text='Your main website.'),
        ),
        migrations.AlterField(
            model_name='profilelinks',
            name='url',
            field=models.URLField(help_text='YouTube, Instagram, Twitter...', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='short',
            name='visibility',
            field=models.CharField(
                choices=[('public', 'Public'), ('unlisted', 'Unlisted')],
                default='unlisted',
                max_length=20,
            ),
        ),
    ]
