# Generated by Django 2.2.11 on 2020-03-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0018_add_job_encoding_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contract_type',
            field=models.CharField(
                choices=[
                    ('full-time', 'Full-time'),
                    ('freelance', 'Freelance'),
                    ('internship', 'Internship'),
                ],
                default='full-time',
                max_length=255,
            ),
        ),
    ]
