# Generated by Django 2.2.11 on 2020-03-26 22:13

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """Set published_at date matching latest update."""
    Post = apps.get_model("dillo", "Post")
    db_alias = schema_editor.connection.alias
    for post in Post.objects.using(db_alias).filter(status='published', published_at__isnull=True):
        post.published_at = post.updated_at
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0019_job_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(null=True, blank=True, verbose_name='date published'),
        ),
        migrations.RunPython(forwards_func),
    ]
