# Generated by Django 2.2.11 on 2020-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0020_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationssettings',
            name='is_enabled_for_comment',
            field=models.BooleanField(
                default=True,
                help_text='Enable if you want to receive emails when someone comments on your content.',
                verbose_name='Email on comments',
            ),
        ),
        migrations.AddField(
            model_name='emailnotificationssettings',
            name='is_enabled_for_follow',
            field=models.BooleanField(
                default=True,
                help_text='Enable if you want to receive emails when someone follows your profile.',
                verbose_name='Email on profile follow',
            ),
        ),
        migrations.AddField(
            model_name='emailnotificationssettings',
            name='is_enabled_for_like',
            field=models.BooleanField(
                default=True,
                help_text='Enable if you want to receive emails about likes on your comments or posts.',
                verbose_name='Email on received likes',
            ),
        ),
        migrations.AddField(
            model_name='emailnotificationssettings',
            name='is_enabled_for_reply',
            field=models.BooleanField(
                default=True,
                help_text='Enable if you want to receive emails when someone leaves a response to your comments.',
                verbose_name='Email on replies to your comments',
            ),
        ),
    ]
