# Generated by Django 2.2.11 on 2020-04-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0021_extend_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationssettings',
            name='is_enabled_for_newsletter',
            field=models.BooleanField(
                default=True,
                help_text='Enable if you want to receive updates about the platform and the community. Follow the Animato journey with us!',
                verbose_name='Receive hand-crafted newsletter.',
            ),
        ),
    ]
