# Generated by Django 2.2.11 on 2020-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0022_email_is_enabled_for_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='date created'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('subject', models.CharField(max_length=150)),
                ('body_txt', models.TextField()),
                ('body_html', models.TextField()),
            ],
            options={'abstract': False,},
        ),
    ]
