# Generated by Django 2.2.11 on 2020-04-23 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0023_add_newsletter'),
    ]

    operations = [
        migrations.AddField(model_name='job', name='notes', field=models.TextField(null=True),),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
