# Generated by Django 2.2.11 on 2020-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0026_event_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden_by_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
