# Generated by Django 2.2.11 on 2020-09-02 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0030_post_rig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostWithMedia',
            fields=[
                (
                    'post_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dillo.Post',
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('dillo.post',),
        ),
    ]
