# Generated by Django 2.2.11 on 2020-12-31 14:16

import dillo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0032_post_media_video_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='url',
            field=models.URLField(
                help_text='A YouTube or Vimeo link',
                max_length=120,
                unique=True,
                validators=[dillo.validators.validate_reel_url],
            ),
        ),
        migrations.AlterField(
            model_name='short',
            name='visibility',
            field=models.CharField(
                choices=[('public', 'Public'), ('unlisted', 'Unlisted')],
                default='public',
                max_length=20,
            ),
        ),
    ]
