# Generated by Django 2.2.11 on 2020-12-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0033_update_shorts'),
    ]

    operations = [
        migrations.DeleteModel(name='PostLink',),
    ]
