# Generated by Django 2.2.11 on 2020-12-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0034_drop_postlink'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE actstream_action ADD COLUMN data jsonb;",
            reverse_sql="ALTER TABLE actstream_action DROP COLUMN data;",
        ),
    ]
