# Generated by Django 2.2.11 on 2021-01-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0036_entity_refactor'),
    ]

    operations = [
        migrations.DeleteModel(name='Rig',),
    ]
