# Generated by Django 2.2.11 on 2021-01-03 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0037_remove_rigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='l_shorts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
