# Generated by Django 2.2.11 on 2021-01-04 01:23

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    """Set published_at date matching latest update."""
    Action = apps.get_model('actstream', 'Action')
    ActionExtra = apps.get_model('dillo', 'ActionExtra')
    Post = apps.get_model('dillo', 'Post')
    try:
        post_content_type = ContentType.objects.get(app_label='dillo', model='post')
    except ContentType.DoesNotExist:
        return
    db_alias = schema_editor.connection.alias
    for action in Action.objects.using(db_alias).filter(
        action_object_content_type_id=post_content_type.id, verb='posted',
    ):
        if not getattr(action, 'action_object_object_id'):
            continue
        try:
            post = Post.objects.using(db_alias).get(pk=action.action_object_object_id)
        except Post.DoesNotExist:
            continue
        if post.is_hidden_by_moderator:
            continue
        ActionExtra.objects.create(action=action, parent_action=None, is_on_explore_feed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
        ('dillo', '0039_remove_shorts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionExtra',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('is_on_explore_feed', models.BooleanField(default=False)),
                (
                    'action',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='extra',
                        to='actstream.Action',
                    ),
                ),
                (
                    'parent_action',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='near_actions',
                        to='actstream.Action',
                    ),
                ),
            ],
            options={'db_table': 'actstream_action_extra',},
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
