# Generated by Django 2.2.14 on 2021-01-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0040_activity_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(help_text='Markdown describing the community.'),
        ),
        migrations.AlterField(
            model_name='community',
            name='tagline',
            field=models.TextField(help_text='A short tagline.'),
        ),
        migrations.CreateModel(
            name='CommunityLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='YouTube, Instagram, Twitter...', verbose_name='URL')),
                ('social', models.CharField(blank=True, max_length=50)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dillo.Community')),
            ],
        ),
    ]
