# Generated by Django 2.2.14 on 2021-01-10 17:42

import dillo.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0041_extend_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='header',
            field=models.ImageField(blank=True, height_field='header_height', help_text='A 16:9 image to use for OpenGraph and others', upload_to=dillo.models.mixins.get_upload_to_hashed_path, width_field='header_width'),
        ),
        migrations.AddField(
            model_name='community',
            name='header_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='header_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', help_text='A 16:9 image to use for OpenGraph and others', upload_to=dillo.models.mixins.get_upload_to_hashed_path, width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='community',
            name='logo_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='logo_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='theme_color',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='community',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', help_text='A 16:9 image to use for OpenGraph and others', upload_to=dillo.models.mixins.get_upload_to_hashed_path, width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='community',
            name='thumbnail_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='thumbnail_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dillo.Community')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('community', 'slug')},
            },
        ),
    ]
