# Generated by Django 2.2.14 on 2021-01-10 17:55

import dillo.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0042_extend_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='header',
            field=models.ImageField(blank=True, height_field='header_height', help_text='A wide image', upload_to=dillo.models.mixins.get_upload_to_hashed_path, width_field='header_width'),
        ),
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', help_text='A square image with the community logo', upload_to=dillo.models.mixins.get_upload_to_hashed_path, width_field='logo_width'),
        ),
    ]
