# Generated by Django 2.2.14 on 2021-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0043_extend_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dillo.CommunityCategory'),
        ),
    ]
