# Generated by Django 2.2.14 on 2021-02-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0045_postmedia_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_link',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
