# Generated by Django 2.2.14 on 2021-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0049_is_pinned'),
    ]

    operations = [
        migrations.AddField(model_name='comment', name='slug', field=models.SlugField(blank=True),),
    ]
