# Generated by Django 2.2.14 on 2021-04-01 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0050_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticasset',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticasset', name='slug', field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='staticasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date edited'),
        ),
    ]
