# Generated by Django 2.2.14 on 2021-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0051_static_asset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='community', name='dillo_uuid', field=models.SlugField(blank=True),
        ),
    ]
