# Generated by Django 2.2.14 on 2021-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0053_static_asset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job', name='dillo_uuid', field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='post', name='dillo_uuid', field=models.SlugField(blank=True),
        ),
    ]
