# Generated by Django 2.2.14 on 2021-04-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0055_static_asset_longer_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job', name='dillo_uuid', field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post', name='dillo_uuid', field=models.SlugField(blank=True, default=''),
        ),
    ]
