# Generated by Django 2.2.14 on 2021-04-08 22:02

import dillo.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0056_dillo_uuid_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField()),
                (
                    'icon',
                    models.ImageField(
                        blank=True,
                        height_field='icon_height',
                        upload_to=dillo.models.mixins.get_upload_to_hashed_path,
                        width_field='icon_width',
                    ),
                ),
                ('icon_height', models.PositiveIntegerField(null=True)),
                ('icon_width', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='badges', to='dillo.Badge'),
        ),
    ]
