# Generated by Django 2.2.14 on 2021-04-08 23:37

import dillo.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0057_badges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge', old_name='icon_height', new_name='image_height',
        ),
        migrations.RenameField(model_name='badge', old_name='icon_width', new_name='image_width',),
        migrations.RemoveField(model_name='badge', name='icon',),
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(
                blank=True,
                height_field='image_height',
                upload_to=dillo.models.mixins.get_upload_to_hashed_path,
                width_field='image_width',
            ),
        ),
    ]
