# Generated by Django 2.2.14 on 2021-04-11 20:57

import dillo.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0058_rename_icon_to_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='A preview image for the entity', upload_to=dillo.models.mixins.get_upload_to_hashed_path),
        ),
    ]
