# Generated by Django 2.2.14 on 2021-06-05 11:02

import dillo.models.mixins
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


def add_default_user(apps, schema_editor):
    """Set published_at date matching latest update."""
    Event = apps.get_model("dillo", "Event")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    db_alias = schema_editor.connection.alias
    for event in Event.objects.using(db_alias).all():
        event.user = User.objects.first()
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dillo', '0060_job_blank_notes'),
    ]

    operations = [
        migrations.RemoveField(model_name='event', name='image_height',),
        migrations.RemoveField(model_name='event', name='image_width',),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='A preview image for the entity',
                upload_to=dillo.models.mixins.get_upload_to_hashed_path,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event', name='dillo_uuid', field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event', name='hash_id', field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='is_pinned_by_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('processing', 'Processing'),
                    ('published', 'Published'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date edited'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(add_default_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(
                null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(
                choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')],
                default='public',
                max_length=20,
            ),
        ),
    ]
