# Generated by Django 2.2.14 on 2021-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0061_event_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community', name='slug', field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterField(
            model_name='communitycategory', name='slug', field=models.SlugField(allow_unicode=True),
        ),
    ]
