# Generated by Django 2.2.14 on 2021-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0062_community_slug_unicode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge', name='name', field=models.CharField(max_length=128),
        ),
    ]
