# Generated by Django 3.2.12 on 2022-07-03 00:47
import sys

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


def load_cities_from_fixture(apps, schema_editor):
    from django.core.management import call_command

    if 'test' in sys.argv:
        return
    # Cities sourced from https://simplemaps.com/data/world-cities
    call_command("loaddata", "cities")


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0066_update_id_to_bigint'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=256)),
                ('name_ascii', models.CharField(max_length=256)),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_ref',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profiles',
                to='dillo.city',
            ),
        ),
        migrations.RunPython(load_cities_from_fixture, migrations.RunPython.noop),
    ]
