# Generated by Django 3.2.14 on 2022-09-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0069_alter_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotificationssettings',
            name='is_enabled_for_newsletter',
            field=models.BooleanField(default=False, help_text='Enable if you want to receive updates about the platform and the community. Follow the journey with us!', verbose_name='Receive hand-crafted newsletter.'),
        ),
    ]
