# Generated by Django 3.2.15 on 2022-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0069_alter_profile_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailnotificationssettings',
            name='is_enabled_for_newsletter',
            field=models.BooleanField(default=False, help_text='Enable if you want to receive updates about the platform and the community. Follow the journey with us!', verbose_name='Receive hand-crafted newsletter.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('review', 'Review')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('review', 'Review')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('review', 'Review')], default='draft', max_length=20),
        ),
    ]
