# Generated by Django 3.2.15 on 2022-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0071_add_spam_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
