# Generated by Django 3.2.14 on 2022-09-03 22:05

from django.db import migrations, models


def set_trust_level(apps, schema_editor):
    """Make all existing active users trusted."""

    from dillo.models.profiles import Profile

    Profile.objects.filter(user__is_active=True).update(trust_level=2)


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0072_alloweddomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trust_level',
            field=models.IntegerField(
                choices=[
                    (0, 'New User'),
                    (1, 'Basic User'),
                    (2, 'Member'),
                    (3, 'Regular'),
                    (4, 'Leader'),
                ],
                default=0,
            ),
        ),
        migrations.RunPython(set_trust_level, migrations.RunPython.noop),
    ]
