# Generated by Django 3.2.13 on 2022-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0074_profile_is_looking_for_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.TextField(blank=True, help_text='Tell us about you. In 80 characters.', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Your life story.', max_length=512),
        ),
    ]
