# Generated by Django 3.2.13 on 2022-11-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0075_profile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, help_text='Tell us about you. In 80 characters.', max_length=80),
        ),
    ]
