# Generated by Django 3.2.13 on 2022-11-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dillo', '0076_profile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_looking_for_work',
            field=models.BooleanField(
                default=False,
                help_text='Your profile will show that you are open to work opporunities.',
                verbose_name='Looking for work',
            ),
        ),
    ]
