# Generated by Django 3.2.13 on 2022-11-19 22:29

import dillo.models.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


def forwards_func(apps, schema_editor):
    """Set default cateogries."""
    OrganizationCategory = apps.get_model('dillo', 'OrganizationCategory')
    db_alias = schema_editor.connection.alias

    for c in {'3D', '2D', 'Features', 'Shorts', 'Games'}:
        OrganizationCategory.objects.using(db_alias).create(name=c)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dillo', '0077_profile_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Organization categories',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='date created'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('name', models.CharField(max_length=255, unique=True)),
                (
                    'visibility',
                    models.CharField(
                        choices=[
                            ('public', 'Public'),
                            ('unlisted', 'Unlisted'),
                            ('under_review', 'Under Review'),
                        ],
                        default='under_review',
                        max_length=16,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='A description of the organization activities.',
                        null=True,
                    ),
                ),
                ('website', models.URLField(max_length=120)),
                (
                    'logo',
                    models.ImageField(
                        blank=True,
                        height_field='logo_height',
                        upload_to=dillo.models.mixins.get_upload_to_hashed_path,
                        width_field='logo_width',
                        help_text='A square picture, around 512x512.',
                    ),
                ),
                ('logo_height', models.PositiveIntegerField(null=True)),
                ('logo_width', models.PositiveIntegerField(null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                (
                    'country',
                    django_countries.fields.CountryField(blank=True, max_length=2, null=True),
                ),
                (
                    'is_online',
                    models.BooleanField(
                        default=False, help_text='Operates fully online, with no physical HQ.'
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'categories',
                    models.ManyToManyField(
                        help_text='Keywords to identify this organization.',
                        null=True,
                        to='dillo.OrganizationCategory',
                    ),
                ),
                (
                    'city_ref',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organizations',
                        to='dillo.city',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
